### ISSUE TITLE
Loading slot section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#10]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48475827-f3edf300-e7fd-11e8-9ab8-6d6226f33441.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48475838-fa7c6a80-e7fd-11e8-963c-c0efd7ea3faf.png)

Screenshot Webflow laptop
![image](https://user-images.githubusercontent.com/22452702/48475881-0ec06780-e7fe-11e8-92cd-3890c2b9b4ea.png)

Screenshot live site laptop
![image](https://user-images.githubusercontent.com/22452702/48475921-1ed84700-e7fe-11e8-8b0e-860f30dd9d32.png)

It is important that the recess shape is as much to the left as possible, so the right side of the image should always be in view.

On the large display there should be less empty space underneath the frame. The height settings on Webflow are 100% with a minimum of 740 pixels.

These two adjustments together should make the frame a bit smaller as well.

The text block has a width of 20% of the browser which gives it nice spacing on both large and small desktop displays

- [x]  Right side of the image always in view
- [x]  Use SlotPG2.png
- [x]  Less empty space underneath the frame. (min) height is 740px
- [x]  Text block as much as possible centered in the empty space left of the frame
- [ ]  Text block width 20%

**TABLET**
Screenshot target Webflow site on iPad Mini
![2018-11-14 11 15 44](https://user-images.githubusercontent.com/22452702/48476217-be95d500-e7fe-11e8-9aae-26c16b9a08cc.png)

Screenshot live site on iPad Mini
![2018-11-14 11 15 52](https://user-images.githubusercontent.com/22452702/48476238-c9506a00-e7fe-11e8-8290-0d48f40c2cc1.png)

- [x]  Right side of the image always in view
- [x]  Use DSC_0154Slothoger.jpg
- [x]  Section should be less tall. (min) height is 660px
- [x]  Text block should be under the frame

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-111748](https://user-images.githubusercontent.com/22452702/48476329-0c124200-e7ff-11e8-8cf4-b94719612783.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-111800](https://user-images.githubusercontent.com/22452702/48476333-0fa5c900-e7ff-11e8-8cec-b445e66903c4.png)

- [x]  Right side of the image always in view
- [x]  Use SlotPhone5.jpg
- [x]  Section should be less tall. (min) height is 360px
- [x]  Text block should be positioned in the middle of the vertical empty space.

**Comment by isaachinman** [comment]
e8a17aa
