### ISSUE TITLE
Compatible prints section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#12]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48477045-dec69380-e800-11e8-8ca7-2437708924be.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48477058-eb4aec00-e800-11e8-83ed-e8a07d63d06f.png)

The current image size on the live site is too small on a large display. Please make it scale like the Webflow site. Webflow settings are 94% width within 58% width div block. Maximum width is 900px.

The text block should be centered in the area right of the image rather than alligned to the viewport middle. It should also be wider: 420px.

There should be more vertical space: Total section height should be 900px

- [ ] Image size scales with browser width. Maximum width is 900px
- [ ] Text block centered in the area right of the image
- [ ] Text block 420px wide
- [ ] Total section height 900 px

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 11 32 41](https://user-images.githubusercontent.com/22452702/48477139-15041300-e801-11e8-916d-ec4cb7a04072.png)

Screenshot live site on iPad Mini
![2018-11-14 11 32 49](https://user-images.githubusercontent.com/22452702/48477146-1b928a80-e801-11e8-99f8-db2e73f3d7e7.png)

- [x] The layout should have a vertical allignment. 
- [x] The image should scale to 80% of width
- [x] 53 pixels between image and text block
- [x] Total section height 880 px

**PHONE**

- [x] The image should scale to 85% of width
- [x] 35 pixels between image and text block
- [x] Total section height 560 px

**Comment by isaachinman** [comment]
I think in general a lot of these issues have to do with a confusion regarding width of layouts, etc. We've constrained all layouts to fall within 1184px (doesn't include background images).

This is a very important point and is not something that can change. Having unrestricted layouts that scale infinitely is not something we can or should do.

**Comment by isaachinman** [comment]
> Image size scales with browser width

The image will scale with breakpoints, not in some unrestricted `vw` way.

**Comment by isaachinman** [comment]
fb47847

**Comment by Tintels** [comment]
DESKTOP

I  wondering, if we need to set a max width, can we increase the number 1184? This section looks unnecessarily cramped

Also, the content does seem to be less wide than 1184 px now. Please make the width of the content as wide as possible. Great if the title can go from 3 to 2 lines. Paragraph from 5 to 4 lines. Larger image.

- [ ] Content as wide as possible

PHONE

Image should be a bit larger
- [ ] The image should scale to 85% of width for this breakpoint

**Comment by isaachinman** [comment]
1c7c18f
