### ISSUE TITLE
What's showing section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#13]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48477384-c014cc80-e801-11e8-8071-cf29fc604f95.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48477398-c7d47100-e801-11e8-98f8-6dfc5a712380.png)

The current image width on the live site is too small on a large display. Please make it scale like the Webflow site. Webflow settings are 65VW. 

Section height is dynamic, allowing full image to remain visible.

The text block should be centered in the area left of the image. On the live site there is more white space on the left compared to right.

- [ ] Image size scales 65VW
- [ ] Dynamic section height
- [ ] Text block centered in the area left of the image

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 11 38 57](https://user-images.githubusercontent.com/22452702/48477461-f2bec500-e801-11e8-8d8a-3e3b0530346f.png)

Screenshot live site on iPad Mini
![2018-11-14 11 39 06](https://user-images.githubusercontent.com/22452702/48477467-f8b4a600-e801-11e8-8303-5e93794fc860.png)

- [x] Full image width should be visible
- [ ] Dynamic section height
- [x] Text  block should appear in the middle of the copy space left of the frame
- [x] Text styling: Center

**PHONE**

I updated the section for phone on Webflow with a taller image allowing text on top of the image rather than isolated on white. This is the image:
https://www.dropbox.com/s/f4v4h1hb3tyt76c/WhatsShowing_phoneNov18.jpg?dl=0

The responsive behaviour on Webflow is not optimized, but this is the goal:

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-114206](https://user-images.githubusercontent.com/22452702/48477668-77114800-e802-11e8-972b-1fe5820dc839.png)

- [x] Update image to WhatsShowing_phoneNov18.jpg
- [x] Full image height and width should be visible on all screens
- [x] New layout: Title and paragraph over image, hashtags paragraph below image on white

**Comment by isaachinman** [comment]
I think in general a lot of these issues have to do with a confusion regarding width of layouts, etc. We've constrained all layouts to fall within 1184px (doesn't include background images).

This is a very important point and is not something that can change. Having unrestricted layouts that scale infinitely is not something we can or should do.

**Comment by isaachinman** [comment]
eaaee73

**Comment by Tintels** [comment]
DESKTOP

Compliments on the left hand responsive cropping of the image! Works well.

TABLET

Plant needs padding on the right

Screenshot target Webflow site on iPad Mini
![2018-11-23 15 00 05](https://user-images.githubusercontent.com/22452702/48947153-85611180-ef30-11e8-8203-91f7223c21e8.png)

Screenshot live site on iPad Mini
![2018-11-23 14 59 51](https://user-images.githubusercontent.com/22452702/48947157-885c0200-ef30-11e8-8405-fd866e0f8c92.png)

- [ ] Full image width should be visible or at least more space to the right of leaf

PHONE

White section with hastags height should decrease a bit. On my phone Live site is 386 and Webflow height is 318.

- [ ]  Decrease white section with hastags height
- [ ] Remove few white pixel height / white line above section:

![screenshot_20181123-150245](https://user-images.githubusercontent.com/22452702/48947294-e4268b00-ef30-11e8-894a-66d9a87d81b2.png)

**Comment by isaachinman** [comment]
> Plant needs padding on the right

The image is like that so that the layout won't break at other resolutions.

**Comment by isaachinman** [comment]
ef436e1
