### ISSUE TITLE
Create a playlist section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#14]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48478007-5c8b9e80-e803-11e8-8366-b4a3301577d2.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48478018-657c7000-e803-11e8-80f2-dcb30565c6d7.png)

The combination of image and text should use more of the browser width like on the Weblfow site:
 Image should move more to the left and text more to the right.

Text should scale wider. Webflow width settings are: Column is 5/12 lof browser width, Text block is 78% of this width moved 20ps to the left.

- [x]  Image should move more to the left and text more to the right.
- [x] Image larger: about 9%.
- [x] Text scales wider
- [x] App store buttons slightly larger.
- [x] More vertical space: 96 pixels above, and 124 pixels below image

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 11 50 31](https://user-images.githubusercontent.com/22452702/48478071-8e046a00-e803-11e8-846f-beb328cd938e.png)

Screenshot live site on iPad Mini
![2018-11-14 11 50 40](https://user-images.githubusercontent.com/22452702/48478092-9492e180-e803-11e8-8e84-d31c42ce6ad9.png)

- [x] More white space left and right

**PHONE**

Add the image between the paragraph and the app store buttons:

- [x] Add image

**Comment by Tintels** [comment]
PHONE

- [ ]  Move the text up a bit. The amount of grey space above the phone image can stay the same. text can move up within this space.
- [ ]  Buttons slightly smaller and lower

**Comment by isaachinman** [comment]
858e1f1
