### ISSUE TITLE
Add to your queue section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#15]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48478225-fbb09600-e803-11e8-9b34-237002cba8cc.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48478252-08cd8500-e804-11e8-999b-c35d8cd2fa0c.png)

On a large display, the image is cropped at the top and bottom. This should be prevented.
On a laptop display the girl should be positioned more to the center.

Screenshot Webflow laptop
![image](https://user-images.githubusercontent.com/22452702/48478364-5a760f80-e804-11e8-8943-7287c5b82a56.png)

Screenshot live site laptop
![image](https://user-images.githubusercontent.com/22452702/48478412-86919080-e804-11e8-8488-48dd094d6b9d.png)

Text should scale wider. Webflow width settings are: Column is 4/12 lof browser width, Text block is 80% of this width.

- [x]  Prevent image cropping, height 800 px
- [x]  Move girl sightly to the left on laptop displays
- [x]  Textblock scales wider
- [x]  Remove semi-transparent white box for cleaner look

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 11 58 38](https://user-images.githubusercontent.com/22452702/48478508-cb1d2c00-e804-11e8-8095-c0153eebdce6.png)

Screenshot live site on iPad Mini
![2018-11-14 11 59 12](https://user-images.githubusercontent.com/22452702/48478713-55659000-e805-11e8-9718-a44ff4b7faa8.png)

The image should be wider, girl will be smaller, allowing more breathing room. 

- [x]  Wider image, smaller girl, height 700 px
- [x]  Move girl sightly to the left
- [x]  Remove dark overlay
- [x]  Black header, dark grey paragraph

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-120026](https://user-images.githubusercontent.com/22452702/48478574-fb64ca80-e804-11e8-8489-33d3aff76e28.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-120042](https://user-images.githubusercontent.com/22452702/48478578-fe5fbb00-e804-11e8-9751-a11fd2e3ac7f.png)

- [x]  Slightly wider image, smaller girl, height 580 px
- [x]  Remove drop shadow from text
- [x]  Text positioned between chin and fingers

**Comment by isaachinman** [comment]
>  Remove dark overlay

Not sure when you changed your webflow project, but the dark overlay came specifically from you.

**Comment by isaachinman** [comment]
>  Remove drop shadow from text

Decreases legibility.

**Comment by isaachinman** [comment]
>  Remove semi-transparent white box for cleaner look

Decreases legibility.

**Comment by isaachinman** [comment]
This is not something we should be striving for:

<img width="301" alt="screen shot 2018-11-14 at 20 49 04" src="https://user-images.githubusercontent.com/10575782/48530906-d1d09100-e84e-11e8-865b-136d50c18251.png">

**Comment by isaachinman** [comment]
86df983

**Comment by Tintels** [comment]
TABLET

I assume you don't like the text half over the girl's shirt. I tweaked the Webflow to prevent that. On the live site the text is too close to the edge.

Screenshot target Webflow site on iPad Mini
![2018-11-23 15 07 35](https://user-images.githubusercontent.com/22452702/48947477-99f1d980-ef31-11e8-99bd-95b5e672b35d.png)

Screenshot live site on iPad Mini
![2018-11-23 15 07 46](https://user-images.githubusercontent.com/22452702/48947483-9e1df700-ef31-11e8-9deb-4d331f141389.png)


- [ ]  Move girl sightly to the right
- [ ]  Move text sightly to the right

PHONE

Screenshot target Webflow site on Nexus 5X
![screenshot_20181123-103235](https://user-images.githubusercontent.com/22452702/48947568-dd4c4800-ef31-11e8-84a8-f4a860d8b059.png)

Screenshot live site on Nexus 5X
![screenshot_20181123-103221](https://user-images.githubusercontent.com/22452702/48947585-e9d0a080-ef31-11e8-8ef4-34936bf5ccdb.png)

It's possible to have pretty much all of the girl in view on most / my phone

- [ ]  All of the girl in view (e.g. shoulders)
- [ ]  Text slightly narrower to get more padding left right

**Comment by isaachinman** [comment]
It's not about text overlapping a person's shirt. It's about basic contrast principles of web design:

> WCAG 2 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text.

**Comment by isaachinman** [comment]
155dad6
