### ISSUE TITLE
Order a pack of prints section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#16]
**DESKTOP**

Little more space below paragraph, image bit smaller.

- [x]  Image a bit smaller: 485 px
- [x]  80px between paragraph and image
- [x]  Background color #FAFAFA

**TABLET**

- [x]  80px between paragraph and image
- [x]  Text block bit wider: 520px
- [x]  Background color #FAFAFA

**PHONE**

- [x]  Image a bit smaller: 70% width
- [x]  66 px whte space below image 
- [x]  Background color #FAFAFA

**Comment by isaachinman** [comment]
3984924
