### ISSUE TITLE
Complete layout freedom section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#18]
**DESKTOP**
Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48479853-ca869480-e808-11e8-890e-6ba8297373e5.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48479862-d40ffc80-e808-11e8-9568-858be2bc5c6c.png)

The current image size on the live site is too small on a large display. On the Webflow desktop site, the image is 95% of the browser width with a maximum of 1460 pixels.

There should be more vertical space

- [x] Increase the spacing above the header to 120 pixels.
- [x] Increase the spacing between the pragraph and the top of the image to 82 pixels.
- [ ] Image width 95%, maximum 1460 pixels 
- [ ] Total section height is 880px
- [x] Decrease paragraph width to 640px
- [ ] Section background should be the tiled texture white_wall.png

**TABLET**
For the tablet break point, the freedom.frame.white.carrer image should be used. The image is 70% of the browser width.

Screenshot target Webflow site on iPad Mini
![2018-11-14 12 29 15](https://user-images.githubusercontent.com/22452702/48479905-fb66c980-e808-11e8-80c8-8b1d24cbf087.png)

Screenshot live site on iPad Mini
![2018-11-14 12 29 27](https://user-images.githubusercontent.com/22452702/48479915-03bf0480-e809-11e8-9407-58e697289d7d.png)

- [x] Set the spacing above the header to 94 pixels.
- [x] Increase the spacing between the pragraph and the top of the image to 46 pixels.
- [x] Use freedom.frame.white.carre image 
- [x] Image 70% browser width 
- [x] Set the spacing below the image to 112 pixels.
- [ ] Section background should be the tiled texture white_wall.png

**PHONE**

- [x] Set the spacing above the header to 55 pixels.
- [x] Increase the spacing between the pragraph and the top of the image to 42 pixels.
- [x] Image 80% browser width 
- [x] Set the spacing below the image to 87 pixels.
- [ ] Section background should be the tiled texture white_wall.png.

**Comment by isaachinman** [comment]
On the web, our max width for all content is 1184px.

**Comment by isaachinman** [comment]
> Section background should be the tiled texture white_wall.png

Again, we'd rather not waste bandwidth on the web by loading a background image like this. If you can find something very small that will tile, let me know.

**Comment by isaachinman** [comment]
f0ee3bf

**Comment by isaachinman** [comment]
It's not a background image, it's content. It fits exactly within our max width:

<img width="1331" alt="screen shot 2018-11-24 at 18 57 00" src="https://user-images.githubusercontent.com/10575782/48974941-ea913180-f01a-11e8-8309-9d0b004ca61b.png">

**Comment by isaachinman** [comment]
7d50738
