### ISSUE TITLE
Showcase art section enhancement

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#19]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48480268-1554dc00-e80a-11e8-9c41-716fc499a554.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48480275-1be35380-e80a-11e8-8013-78dd58a372c9.png)

The current image width on the live site is too small on a large display. Please make it scales like the Webflow site and allign to the left. In Webflow it is inside a div block that is 60% browser width with a maximum of 1015 px including 40px padding on the left

Section height is dynamic, with 40 px above and below image.

The text block should be centered in the area right of the image. 
 Maximum paragraph width should be a little bit wider.

- [ ] Image size scales 60% browser width with a maximum of 1015 px including 40px padding on the left
- [ ] Image alligned to the left.
- [ ] Dynamic section height with 40 px above and below image.
- [ ]  The text block centered in the area right of the image. 
- [ ]  Maximum paragraph width should be a little bit wider.

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 12 38 31](https://user-images.githubusercontent.com/22452702/48480376-741a5580-e80a-11e8-8254-85de2f188738.png)

Screenshot live site on iPad Mini
![2018-11-14 12 39 03](https://user-images.githubusercontent.com/22452702/48480381-78467300-e80a-11e8-9000-5bc20be6a067.png)

- [x]  Consistent spacing (40px) on top, left and right of the image
- [x]  Text block a little less wide

**PHONE**

- [x]  Image covers fulll width
- [x]  Title below image

**Comment by isaachinman** [comment]
On the web, our max width for all content is 1184px.

**Comment by isaachinman** [comment]
5f40f62

**Comment by isaachinman** [comment]
Are you saying you want to modify the image to be a background image, without margins? That's the only way it'd work. If so, please open a different ticket, as that is a new layout change request.

**Comment by isaachinman** [comment]
7e5735e
