### ISSUE TITLE
Dutch about page is in English

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#2]
**Describe the bug**
Dutch about page is in English

**To Reproduce**
1. Go to https://www.wundershine.com/nl/about

**Expected behavior**
Text in Dutch

**Screenshots**

**Browser (please complete the following information):**
 - Device: [e.g. Macbook Pro 2015]
 - Browser: [e.g. Chrome 69.0.3497.100]

**Additional context**

**Comment by isaachinman** [comment]
3df4adc
