### ISSUE TITLE
Getting started section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#20]
**DESKTOP**

I created a horizontal layout for the desktop version of this section after all for better visibility.

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48480615-5699bb80-e80b-11e8-875e-d4493451ba5a.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48480645-6913f500-e80b-11e8-81ec-ae87adf16dbb.png)

- [ ]  Implement the horizontal layout like http://wsnsp.webflow.io/
- [x]  Update text style SKUs: "Reframe" and "Reframe 3-Pack"; Volkorn regular 32 pt
- [x]  Update text style prices; Open Sans normal 25 pt. No superscript.
- [ ]  Segment with SKUs scales 85% browser width
- [ ]  Please note that the button text size is 13pt, consistent with Shopify theme.
- [x]  The background should not be the vignette style gradient but solid #eaeaea

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 12 48 18](https://user-images.githubusercontent.com/22452702/48480729-a37d9200-e80b-11e8-98b2-12a00f41f157.png)

Screenshot live site on iPad Mini
![2018-11-14 12 48 30](https://user-images.githubusercontent.com/22452702/48480737-aa0c0980-e80b-11e8-9d09-82a7c85d60d8.png)

The tablet breakpoint for this section got messed up because of the horizontal change of the desktop layout. I did not fix that because you can use the backup Webflow project for reference: http://wsnspbo.webflow.io/

Tweaks:

- [x]  Little less empty space over title: 85 px
- [ ]  Update text style Title: Getting started"
- [x]  Paragraph wider: 500px
- [x]  Update text style SKUs: "Reframe" and "Reframe 3-Pack"; Volkorn regular 30 pt
- [x]  Segment with SKUs needs to be a bit less wide. Webflow: Two colums together scale to 90% browser width. Within the column the image fills 85% of width.
- [x]  Update text style prices; Open Sans normal 25 pt. No superscript.
- [x]  The background should not be the vignette style gradient but solid #eaeaea

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-125212](https://user-images.githubusercontent.com/22452702/48480933-328aaa00-e80c-11e8-880d-e132a402083a.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-125225](https://user-images.githubusercontent.com/22452702/48480943-36b6c780-e80c-11e8-9130-249f6d46efaf.png)

Please also use  http://wsnspbo.webflow.io/ here for reference.

Tweaks:

- [ ]  Update text style Title: Getting started"
- [x]  Update text style SKUs: "Reframe" and "Reframe 3-Pack"; Volkorn regular 26 pt
- [x]  Segment with SKUs needs to be a bit less wide. Webflow: The column scales to 96% browser width. Within the column the image fills 65% of width.
- [x]  Update text style prices; Open Sans normal 22 pt. No superscript.
- [x]  The background should not be the vignette style gradient but solid #eaeaea

**Comment by isaachinman** [comment]
Sorry, but I really do not understand the point of this. Why change the layout to this horizontal layout (which looks a lot worse, in my opinion) to save space, but _only on desktop_, and still use the vertical layout on tablet and mobile?

Tablet and mobile are the only places where space is a genuine concern in the first place.

**Comment by isaachinman** [comment]
> Update text style Title: Getting started"

Unclear.

**Comment by isaachinman** [comment]
The point of that comment is that it barely fits my 15" laptop, so how will it ever fit on a phone or tablet.

**Comment by isaachinman** [comment]
b7f9d7a
