### ISSUE TITLE
App page enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#22]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48483671-6073ec80-e814-11e8-9dd4-53766e425357.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48483680-68339100-e814-11e8-8d05-262d66aea06f.png)

- [x] Move the content up like Webflow. The position of "THE APP" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [x] The background should be solid #fafafa
- [x] Prints image should have same position as Webflow
- [x] Text block a bit less wide
- [x] Bold text "use the app.." should be 36 pt line height 44, like the hero section on the homepage.
- [x] Vertical size of Google Play button should match the App Store (it's taller now)

**TABLET**

- [x] Move the content up like Webflow. The position of "THE APP" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [x] The background should be solid #fafafa
- [x] Prints image should have same position as Webflow
- [x] Vertical size of Google Play button should match the App Store (it's taller now)

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-135626](https://user-images.githubusercontent.com/22452702/48483960-26571a80-e815-11e8-8a85-2f791f0c18bd.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-135602](https://user-images.githubusercontent.com/22452702/48483965-29520b00-e815-11e8-8105-7dcb24a64287.png)

- [x] The background should be solid #fafafa
- [x] Prints image should have same position as Webflow
- [x] Buttons need to be smaller and side by side. They should be larger than the Webflow site though, and better centered.
- [x] Vertical size of Google Play button should match the App Store (it's taller now)

**Comment by isaachinman** [comment]
de3474f

**Comment by Tintels** [comment]
DESKTOP

It's satisfying / clean when the vertical position of the headers in caps have an exact match. It needs to move down a bit to accomplish that. Pretty sure it's 11 px.

- [ ] The position of "THE APP" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [ ] Caps Header h2 "THE APP" line spacing should be 44px for more spacing. This should cascade down to tablet and phone as well

TABLET

Header style needs to be the same as "Smart Picture Framing" on homepage.

- [ ] Header text size should be 34px
- [ ] Header line spacing should be 38px
- [ ] Text block a bit wider

PHONE

Header style needs to be the same as "Smart Picture Framing" on homepage.

- [ ] Header text size should be 26px
- [ ] Header line spacing should be 30px
- [ ] Text block a bit wider. Same as Creative page on live site. Header can get back to 3 lines on my / most phones like Webflow.

**Comment by isaachinman** [comment]
Matching the Shopify page is going to be a moving target and not something we should focus on.

**Comment by isaachinman** [comment]
980fba2
