### ISSUE TITLE
Creative page enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#23]
**DESKTOP**

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48484423-666acd00-e816-11e8-9221-ac98b2d1df7f.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48484439-72568f00-e816-11e8-9e8c-fec4833a6edf.png)

- [x] Move the content up like Webflow. The position of "CREATIVE" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [x] The background should be solid #ffffff
- [x] Intro text block much wider. 72% max 1000px
- [x] Bold text "Be both.." should be 36 pt line height 44, like the hero section on the homepage.
- [ ] Third party app content should have same position as Webflow
- [ ] App example sections: Wider (60% width)
- [ ] App example sections: More white spacing between elements like Webflow
- [ ] App example sections: More horizontal white spacing like Webflow
- [ ] App example sections: More vertcial white spacing like Webflow
- [ ] Larger app screenshots

**TABLET**

Screenshot target Webflow site on iPad Mini
![2018-11-14 14 07 57](https://user-images.githubusercontent.com/22452702/48484578-c6617380-e816-11e8-830b-e278514c9943.png)

Screenshot live site on iPad Mini
![2018-11-14 14 08 09](https://user-images.githubusercontent.com/22452702/48484580-c9f4fa80-e816-11e8-9695-97df032c110c.png)

- [x] Move the content up like Webflow. The position of "CREATIVE" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [x] The background should be solid #ffffff
- [x] Intro text block much wider. 88% width
- [ ] Third party app content should have same position and centered layout like Webflow
- [ ] Third party app content should have sizing, spacing, layout like Webflow
- [ ] Larger app screenshots

**PHONE**

Screenshot target Webflow site on Nexus 5X
![screenshot_20181114-141003](https://user-images.githubusercontent.com/22452702/48484693-13454a00-e817-11e8-99d3-4a1e9dea2057.png)

Screenshot live site on Nexus 5X
![screenshot_20181114-141016](https://user-images.githubusercontent.com/22452702/48484702-1809fe00-e817-11e8-979e-e03eb6195af3.png)

- [x] Move the content up like Webflow. The position of "CREATIVE" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [x] The background should be solid #ffffff
- [x] Third party app content should have same position and centered layout for all elements like Webflow
- [x] Frame images should be less wide
- [ ] App example sections: More vertcial white spacing like Webflow
- [ ] Larger app screenshots

**Comment by isaachinman** [comment]
>  Third party app content should have same position as Webflow

Unclear.

**Comment by isaachinman** [comment]
> App example sections: Wider (60% width)

They're going to be exactly as wide as the hero content.

**Comment by isaachinman** [comment]
> App example sections: More white spacing between elements like Webflow

These kind of comments are very unclear. What elements? Please be as specific as possible, including percentage increase/decrease. I don't want to do this 2-3 times.

**Comment by isaachinman** [comment]
> Larger app screenshots

The screenshots were made to be _exactly the same size as your Webflow project_.

**Comment by isaachinman** [comment]
bf7c499

**Comment by Tintels** [comment]
DESKTOP

_Intro_
It's satisfying / clean when the vertical position of the headers in caps have an exact match. It needs to move down a bit to accomplish that. Pretty sure it's 11 px.

- [ ] The position of "CREATIVE" should match the position of "PRODUCTS" on the Shopify homepage for consistency.
- [ ] Caps Header h2 "CREATIVE" line spacing should be 44px for more spacing. This should cascade down to tablet and phone as well.
- [ ] Remove line break for one large paragraph and a cleaner look

_App example sections_

Layout is unnecessarily cramped on large display especially. The size difference of the screenshots is visible only on large display.

Screenshot Webflow large display
![image](https://user-images.githubusercontent.com/22452702/48982492-9736e600-f0e3-11e8-9ba6-19311c455177.png)

Screenshot live site large display
![image](https://user-images.githubusercontent.com/22452702/48982494-9dc55d80-f0e3-11e8-9c4d-00c3ce5255a6.png)

Screenshot Webflow laptop
![image](https://user-images.githubusercontent.com/22452702/48982503-b9c8ff00-f0e3-11e8-8df8-96e89e88d6ad.png)

Screenshot live site laptop
![image](https://user-images.githubusercontent.com/22452702/48982513-d5340a00-f0e3-11e8-9d44-76f500dd2187.png)

Layout can fill pretty much the full (1084) width. 

- [ ] App example sections: Add space between the frames and the details on the right
- [ ] App example sections: More vertical white spacing like Webflow. 100px below and above the frames.
- [ ] App example sections: App description paragraphs a little wider.

TABLET

_Intro_
Header style needs to be the same as "Smart Picture Framing" on homepage.

- [ ] Header text size should be 34px
- [ ] Header line spacing should be 38px

_App example sections_

- [ ] Layout like already implemented for phone
- [ ] Larger app screenshots

PHONE

_Intro_
Header style needs to be the same as "Smart Picture Framing" on homepage.

- [ ] Header text size should be 26px
- [ ] Header line spacing should be 30px

_App example sections_

- [ ] Larger app screenshots

**Comment by isaachinman** [comment]
a28169e
