### ISSUE TITLE
Header / navigation enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#24]
**DESKTOP**

The header should use the full width of the browser.

- [ ] Header full width
- [x] Logo should be slightly (about 6%) smaller
- [x] Total header height 76 px
- [x] Padding for menu items left, right is 18 px
- [x] Button text update: SHOP NOW

**TABLET**

**PHONE**

Please replace the hamburger menu icon. Should be smaller and the current one has light grey cross lines.  Ideally the icon resembles the Shopify icon as close as possible. Let me know if I need to look for one.

- [x] Use logo with wundershine text like Webflow
- [x] Replace hamburger menu icon. 

The phone menu test should be smaller. Ideally the menu resembles the Shopify menu as close as possible for consistency

- [x] Phone menu smaller text style
- [x] Phone menu style as close as possible to the Shopify style

**Comment by Tintels** [comment]
DESKTOP

I believe you asked for more detail on the full header width. In Webflow I have 32px space on the left of the logo, and 40 px on the right of the button. I see they do fall partlly behind the scroll bar.

**Comment by isaachinman** [comment]
On the web, our max width for all content is 1184px.
