### ISSUE TITLE
Link to the correct Shopify (Weglot) language version

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#29]
As mentioned in issue #28 , I'd like to go with the free Weglot for the time being. The free plan does not have the auto language switch. It would be great if we can link to the correct language version of our Shopify shop. So English website to English shop and Dutch to Dutch.

Please check if this is possible. It may not be, as I can't see a difference in URL for the Dutch and English language version of our shop.

**Comment by isaachinman** [comment]
The URLs would need to be different. It may be a query param - can you please check and let me know?

**Comment by Tintels** [comment]
Mm. I wouldn't know how to do that. Did you see the language switcher on the shop page bottom left?

**Comment by isaachinman** [comment]
The language is being stored in a cookie - we cannot do anything about this.
