### ISSUE TITLE
Playlist for your wall section | Image missing at mobile breakpoint

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#3]
**Describe the bug**
Playlist for your wall section | Image missing at mobile breakpoint

**To Reproduce**
1. Go to 'Playlist for your wall section'

**Expected behavior**
Image of phone with app with queue visible

**Screenshots**

**Browser (please complete the following information):**
 - Device: [e.g. Macbook Pro 2015]
 - Browser: [e.g. Chrome 69.0.3497.100]

**Additional context**

**Comment by isaachinman** [comment]
It's not missing, it was removed. That image is not going to work on mobile resolutions.
