### ISSUE TITLE
Prepare JSON file access for a few more translations

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#30]
We discussed his briefly here
https://wundershine.slack.com/archives/D98JF3694/p1544466070001700

Prepare JSON files for translating directly in those files and instructions. So we are ready when we want some translator to do it early next year. Let's start with:

French
German
Spanish
Italian
Polish
Swedish
Danish

Perhaps you can make it so that putting a language live and making a language appear in our dropdown menu (once a translation is done) is really a matter of "flipping a switch" / few minutes work for you.

**Comment by isaachinman** [comment]
It _is_ a matter of a few minutes work for me.

The files can already be accessed [here](https://github.com/isaachinman/wundershine-web-app/tree/master/src/static/locales). Simply copy/paste the `en` directory to `fr` (for example), and translate all the English into French.

**Comment by Tintels** [comment]
Mm. Can't find how to do that (quickly) in the browser I can't select the directory. Perhaps I need the Github desktop app?

**Comment by Tintels** [comment]
Not plannnig to arrange translations now, but I assume it is possible to open and edit those files also in some editor  with color indications for the UI text / copy?

**Comment by isaachinman** [comment]
You would need to download the entire repository as a zip file, and navigate to the folder you want. From there you can use any text editor you'd like.
