### ISSUE TITLE
Only 2 taps changes Reframe color on iOS

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#31]
**Describe the bug**
Changing the colors in "The Reframe" section requires two taps on iPad. 

**To Reproduce**
1. Go to The Reframe" section on iPad, (iPhone?)
2. Tap on colored ball
4. See that image does not change

**Expected behavior**
Single tap changes color. Same behaviour as Android

**Screenshots**
-

**Browser (please complete the following information):**
 - Device: [iPad Mini]
 - Browser: [e.g. Chrome, Safari]

**Additional context**
BONUS REQUESTS
If you are looking at this code I have added two nice-to-have have requests:

Cross-fade transitions with color change. References:
https://www.roland.com/global/products/kiyola_kf-10/
https://www.apple.com/iphone/compare/

On Android, Chrome a unsightly square appears when tapping the balls. Can this be hidden?

- [ ] One tap changes Reframe color on iOS
- [ ] Cross-fade transitions with color change
- [ ] Hide unsightly square when tapping the balls on Android

**Comment by isaachinman** [comment]
5ba744e
