### ISSUE TITLE
The Reframe section enhancement

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#33]
Screenshot target Webflow site on Nexus 5X
![screenshot_20181220-103550](https://user-images.githubusercontent.com/22452702/50287203-2aa0d400-0462-11e9-98be-dcee6b08c520.png)

Screenshot live site on Nexus 5X
![screenshot_20181220-103539](https://user-images.githubusercontent.com/22452702/50287210-342a3c00-0462-11e9-8902-920ff755d74a.png)

PHONE

- [x] Decrease Reframe image size a bit

**Comment by isaachinman** [comment]
fff3575
