### ISSUE TITLE
Showcase art section enhancement

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#36]
This is a continuation of issue #19

I have updated the Showcase art section for desktop on http://wsnspbo.webflow.io/

It now has the image as a background in order to make the left allignment possible. You mentioned that there can be no margins. If you can not implement similar code for the position of the image in the webflow page, please let me know and I can create margins in the image itself with either white or alpha pixels.

DESKTOP

- [ ] Move image to the background
- [ ] Image height 600px
- [ ] Image left allignment with 40px left, top and bottom

Please ignore the tablet and phone breakpoints for this section on http://wsnspbo.webflow.io/. These break points should/can remain as they are on the live site.

**Comment by isaachinman** [comment]
> Are you saying you want to modify the image to be a background image, without margins? That's the only way it'd work.

I made it quite clear - will only work without margins. Adding white margins to the image will not work. This is because of the way the layout will reflow at different resolutions.
