### ISSUE TITLE
Creative page enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#37]
DESKTOP

Vertical space above and below frame images should both be 100px both. I think it's 60 and 70 now.
Reference Webflow: http://wsnsp.webflow.io/creative

- [x] Increase vertical spacing between Reframe images to 2 times 100px

TABLET

Screenshot target Webflow site on iPad Mini
![2018-12-20 11 07 51](https://user-images.githubusercontent.com/22452702/50287563-6daf7700-0463-11e9-9a28-2faf06f949b5.png)

Screenshot live site on iPad Mini
![2018-12-20 11 07 36](https://user-images.githubusercontent.com/22452702/50287575-74d68500-0463-11e9-898a-58306fe844dc.png)

- [x] Decrease frame image size
- [x] Decrease app icon size
- [x] Decrease text width

PHONE
- [ ] No (cascading) layout change please

**Comment by isaachinman** [comment]
> No (cascading) layout change please

I don't understand what this means.

**Comment by isaachinman** [comment]
5d01c89
