### ISSUE TITLE
Layout tweaks intro

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#6]
After this intro, I will post layout tweaks per section/page.

The goal/example is http://wsnsp.webflow.io/.

I no longer paid attention to the horizontal smartphone layout on the Webflow site. However, strangely enough, when scaling back the browser on desktop, it will display the _horizontal_ phone layout only. Please ignore that and use the screenshots and/or a real phone for smartphone portrait layout reference.

I have created a new project of the Webflow site and made some optimizations after the October handover. Mostly this: In the October handover version, some of these images turned out too large on (smaller) laptop displays, so I changed the size / responsive scaling.

I also created a better, horizontal layout for "Get started" section that fits better on laptop displays.

For the layout tweaks in general, please note that the (desktop) design is based on a set of relevant modern product promotion pages with large images and the use of the full browser width, not so much centered towards the middle.

Some examples here:

https://store.google.com/product/google_wifi
https://cowboy.com/
https://www.withings.com/nl/en/steel-hr-sport
https://www.canon-europe.com/cameras/eos-r/

Two requests for starters:

The current favicon is stretched out vertically. Please use the one that I uploaded for Shopify: https://www.dropbox.com/s/jh8bm3ag2f5i510/WS_Favicon_trans_32.png?dl=0

For the time being, I'd like to remove the Intercom chat UI from the smartphone breakpoint. It is too distracting on the small screen.

- [x] Replace Favicon
- [x] Remove Intercom from smartphone

**Comment by isaachinman** [comment]
826a718

**Comment by isaachinman** [comment]
9d0b759

**Comment by Tintels** [comment]
General remarks for this round: 

When I suspect that a thing will cascade down to tablet and/or smartphone, I did not (yet) make a mention of it.

I created notes with a repeat of the tasks if relevant, so you can ignore the content / tasks list higher up in the issue.

I do not yet have the rights to manage assignees.

- [ ] Assign rights to me

**Comment by isaachinman** [comment]
I already sent you a collaborator invite awhile ago.
