### ISSUE TITLE
Homepage text styling

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#7]
The adjustments below refer to the styling of standard sections on the homepage.

DESKTOP

- [x] Paragraph line spacing should be 24px
- [x] Less space between header and paragraph. It should be 22 pixels (edited)

TABLET

- [x] Header text size should be 30px
- [x] Header line spacing should be 34px

- [x] Paragraph line spacing should be 22px
- [x] Less space between header and paragraph. 22 rather than 20 pixels 

PHONE

- [x] Header text size should be 22px
- [x] Header line spacing should be 28px

- [x] Less space between header and paragraph. 16 pixels.

**Comment by isaachinman** [comment]
>  Less space between header and paragraph. 22 rather than 20 pixels

Do you mean more space? Where are you getting these pixel values?

**Comment by isaachinman** [comment]
> Header text size should be 30px

What's a "header"? We've got h1 and h2s on the homepage

**Comment by isaachinman** [comment]
>  Paragraph text size should be 16px

It already is 16px. Can you please clarify?

**Comment by Tintels** [comment]
> > Less space between header and paragraph. 22 rather than 20 pixels
> 
> Do you mean more space? Where are you getting these pixel values?

This is inside Webflow:

![image](https://user-images.githubusercontent.com/22452702/48513942-78bc2980-e85d-11e8-9d57-b59eb26e7ba0.png)

You can see the tooltip where the cursor was: Adjust top margin. That's where I got the 22 pixels. 

You can log in with these credentials:
mick@wundershine.com
D88X#jal
Project name: Wundershine Production

But my description does indeed have a mistake. The space should become less, not more. I believe 7 pixels less. 


> > Header text size should be 30px
> 
> What's a "header"? We've got h1 and h2s on the homepage

**h2**




> > Paragraph text size should be 16px
> 
> It already is 16px. Can you please clarify?

You are right. I'll take it out of the list.

**Comment by isaachinman** [comment]
b4644d6
