### ISSUE TITLE
Refresh at will section enhancements

### ISSUE THREAD

**Issue by Tintels** [isaachinman/wundershine-web-app#9]
**DESKTOP**

The current image size on the live site is too small on a large display. On the Webflow desktop site, the image is 77% of the browser width with a maximum of 1360 pixels.

There should be more vertical space: 70 pixels between the paragraph and the top of the image and 130 pixels below the image.

- [x] Increase the spacing between the pragraph and the top of the image to 70 pixels.
- [ ] Image width 77%, maximum 1360 pixels 
- [x] 130 pixels below image
- [x] Section background should be #FAFAFA

**TABLET**
For the tablet break point, the Refreshphone.png image should be used. The image scales to width with 58 pixels padding left and right and 110 pixels below the image.

Screenshot target Webflow site on iPad Mini
![2018-11-14 11 03 31](https://user-images.githubusercontent.com/22452702/48475424-0ca9d900-e7fd-11e8-90a3-899d820bc4e2.png)

Screenshot live site on iPad Mini
![2018-11-14 11 03 46](https://user-images.githubusercontent.com/22452702/48475440-159aaa80-e7fd-11e8-8be0-8e725e8873a8.png)

- [x] Paragraph should remain three lines. Webflow has 540 px width.
- [x] Replace image with Refreshphone.png
- [x] Scale to width with 58 pixels padding left and right and 110 pixels below the image.
- [ ] With this setting, move the image 4 px to the right for visual centre of the two frames 

**PHONE**
Image needs a bit more space / padding.

- [ ] Scale to width with 18 pixels padding left and right and 74 pixels below the image.
- [ ] With this setting, move the image 4 px to the right for visual centre of the two frames

**Comment by isaachinman** [comment]
On the web, our max width for all content is 1184px.

**Comment by isaachinman** [comment]
> Refreshphone.png image

Please provide image.

**Comment by Tintels** [comment]
> > Refreshphone.png image
> 
> Please provide image.

https://www.dropbox.com/s/ierlnon21dvbq4l/Refreshphone.png?dl=0

**Comment by isaachinman** [comment]
>  With this setting, move the image 4 px to the right for visual centre of the two frames

This is not the kind of request we'll be doing.

**Comment by isaachinman** [comment]
4689465

**Comment by Tintels** [comment]
TABLET

There is something wrong with the resolution of the image. Very visible on retina iPad or screenshot below @ 100%.

Screenshot target Webflow site on iPad Mini
![2018-11-25 12 48 07](https://user-images.githubusercontent.com/22452702/48982306-fa734900-f0e0-11e8-9ed2-39b0d51477dc.png)

Screenshot live site on iPad Mini
![2018-11-25 12 48 15](https://user-images.githubusercontent.com/22452702/48982307-03641a80-f0e1-11e8-9e11-a8f9ebd90103.png)

- [ ] Fix image resolution
- [ ] Image bit smaller / more spacing left right 

PHONE

Pretty sure the image has the same resolution issue.

Please make sure that the image did not become smaller on the phone followong the tablet adjustment. On phone it could actually be tiny bit larger.

- [ ] Fix image resolution

**Comment by isaachinman** [comment]
65a26a3
